### ISSUE TITLE
Proposed changes to rewardContributor() method

### ISSUE THREAD

**Issue by KelseyCarlow** [git-token/contracts#10]
https://github.com/git-token/contracts/issues/8 proposes removing reward values from the contract itself.

This will require adding two additional values to the `rewardContributor()` method:

Additionally, I propose: 

- Remove the reservedType from the parameters list if no longer using for a value lookup;
- Remove the rewardBonus parameter and include the value in the rewardValue

```
/**
   * @dev Reward contributor when a GitHub web hook event is received
   * @param  _username      string  GitHub username of contributor
   * @param  _rewardType    string  GitHub web hook event
   * @param  _rewardValue   uint     Number of tokens rewarded to contributor
   * @param  _reservedValue uint    Number of tokens reserved for auction
   * @param  _deliveryID       string GitHub delivery ID of web hook request
   * @return                            bool   Returns boolean value if method is called
   */
  function rewardContributor(
    string _username,
    string _rewardType,
    uint _rewardValue,
    uint _reservedValue,
    string _deliveryID
  ) ...
```

https://github.com/git-token/contracts/blob/d62f4a5efdb01db70b2701dbe63682f77ffdc963/contracts/GitToken.sol#L407

**Comment by Ryanmtate** [comment]
https://github.com/git-token/contracts/pull/14

Merged in proposed changes and updated unit tests
